// <auto-generated />
namespace laba4_POP3_server_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addmessages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmessages));
        
        string IMigrationMetadata.Id
        {
            get { return "201703282157368_add messages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
